#!/usr/bin/env bash
# Configure Nginx so that its HTTP header shows "X-Served-By <hostname>"
# where hostname is the name of the server

# install nginx and ufw
sudo apt-get update
sudo apt-get -y install nginx
sudo apt-get -y install ufw

# configure firewall to allow Nginx receive HTTP requests
sudo ufw allow 'Nginx HTTP'

# make html dir
sudo mkdir -p /var/www/html

# change permissions of the dir
sudo chmod -R 755 /var/www

# create index page
sudo echo 'Hello World!' > /var/www/html/index.html

# create error page
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

# configure servee block
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root /var/www/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 https://youtube.com;
	}
	error_page 404 /404.html;;
	location /404 {
		root var/www/html;
		internal;
	}
}"

sudo echo $SERVER_CONFIG > /etc/nginx/sites-available/default

sudo service nginx restart
