#!/usr/bin/env bash
# Installs and configures HAproxy

sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*;

echo "ENABLE=1" >> /etc/default/haproxy;

CONFIG=\
"global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend akt_global_frontend
	bind *:80
	mode http
	default_backend akt_global_servers

backend akt_global_servers
	timeout connect 3000
	timeout server 30000
	balance roundrobin
	server 323139-web-01 100.26.9.42:80 check
	server 323139-web-02 54.237.115.35:80 check
"

echo "$CONFIG" > /etc/haproxy/haproxy.cfg;

if [ "$(pgrep -c haproxy)" -le 0 ]; then
        sudo service haproxy start
else
        sudo service haproxy restart
fi
