#!/usr/bin/env bash
# A bash script that manages the manage_my_process script
# it takes any of the following commands

# start: starts the manage_my_process script
#	stores its PID in /var/run/my_process.pid
#	displays "manage_my_process started"
# stop: stops the manage_my_process script
#	deletes the file /var/run/my_process.pid
#	displays "manage_my_process stopped"
# restart: stops the manage_my_process script
#	deletes the manage_my_process script
#	starts the manage_my_process script
#	stores its PID in /var/run/my_process.pid
#	displays "manage_my_process restarted"
if [ "$1" == "start" ]
then
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
