#!/usr/bin/env bash
#installs a firewall and opens ports 22, 80, 443

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo service ufw start
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo service ufw restart
