#!/usr/bin/env bash
# changes the home address to 127.0.0.2
# resolves facebook.com to 8.8.8.8

sudo cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
